name: JavaScript Workflow

on: [push, pull_request]

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    - use: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
    - run: npm install
    - name: Run Prettier
    - run: npm run format
    - name: Run ESLint
    - run: npm run lint
    - name: Run tests
    - run: npm run test
